### PR TITLE
Fix game type value

### PR DESCRIPTION
**Pull request by jhare**
The template value for game type was being passed instead of 'chess'

### CODE REVIEW

**Comment by JacobFischer** [comment]
This PR looks correct, why did you close it?

**Comment by jhare** [comment]
@JacobFischer Adam said that it would have been set if our solution repositories were generated with the `.js` client included. I cloned mine down separately into a chess implementation and did make this change locally, but at the repo level I'm told this is correct. They included C++, Java, C#, Python by default. Thanks for asking!

**Comment by JacobFischer** [comment]
Ah yeah that's outside the scope of this repo.

I'm still going to merge this PR, as this is an oversight I should have made on this branch. It's a good catch!

**Comment by jhare** [comment]
Thanks!

**Pull request merged**
